### ISSUE TITLE
Infrastructure Modification check ignores conditions set on policy

### ISSUE THREAD

**Issue by ghost** [salesforce/cloudsplaining#278]
It appears that the checks for **Infrastructure Modification** report actions even when conditions apply - while, on the other hand, the checks for e.g. **Data Exfiltration** and **Privilege Escalation** *do not* flag actions when conditions apply.

**This causes false negatives** when we have a policy that, for example, allows `ec2.RunInstances` but includes a condition that `ec2:Owner` must be a certain account; such a policy has been crafted deliberately, but Cloudsplaining still flags it as allowing Infrastructure Modification.

To reproduce, consider this policy:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:RunInstances"
      ],
      "Condition": {
        "StringEquals": {
            "ec2:Owner": "ValidOwnerId"
          }
      },
      "Resource": "*",
      "Effect": "Allow"
    },
    {
        "Effect": "Allow",
        "Action": "s3:GetObject",
        "Condition": {
            "StringEquals": {
                "ec2:Owner": "ValidOwnerId"
              }
          },
        "Resource": "*"
    },
    {
        "Effect": "Allow",
        "Action": "glue:updatedevendpoint",
        "Condition": {
            "StringEquals": {
                "ec2:Owner": "ValidOwnerId"
              }
          },
        "Resource": "*"
    }
  ]
}
```

If we remove those `Condition` blocks, Cloudsplaining identifies 3 issues: 
![cs-detects-issues](https://user-images.githubusercontent.com/111302707/184683752-e97066c5-0517-48b2-8520-f5a54b9c2407.png)

After adding the `Conditions`, Data Exfiltration and Privilege Escalation disappear, but Infrastructure Modification remains:
![cs-detects-im](https://user-images.githubusercontent.com/111302707/184683747-2264ff43-f968-4744-9679-03710dabe1fe.png)

**Expected Behaviour:** The presence of Conditions causes Cloudsplaining to suppress Infrastructure Modification warnings.

**Actual Behaviour:** Cloudsplaining reports Infrastructure Modification even though Conditions exist on the policy.

**Comment by kmcquade** [comment]
This was by design to reduce noise.

you can skip this behavior by using the `--flag-all-risky-actions` flag in the `scan` command

**Comment by kmcquade** [comment]
Ohhh, I get what you are saying now.

**Comment by kmcquade** [comment]
Ohhh, I get what you are saying now. Thank you for clarifying.

I tried it on a test file with those contents, and what you are saying is correct.

![image](https://user-images.githubusercontent.com/3422255/207168931-1b7b2332-8ddd-45a0-bd95-850b0d90f33b.png)

I think this can be broken down into two issues:
1. The `scan-policy-file` command should have a `--flag-all-risky-actions` flag, just like the `scan` command.
2. As you said, the Infrastructure Modification warning should behave just like Privilege Escalation, Resource Exposure, and Data Exfil. 

To be honest, I am not sure why this is happening. I agree that it shouldn't return warnings for policies where Condition constraints exist. However, I don't really have the time to fix this bug since I am no longer working in that space and I am focusing on my own startup. I responded because it looked important and I felt like it was important to clarify. I wish I could fix that but I just don't have the time.

Despite that limited availability, if you or anyone else wanted to fix this bug and made a PR, I'd be happy to approve a PR that fixes it, provided it has unit tests and is reasonable. If you'd like to take that on, I would encourage you to do so. I'm sorry I can't help more than that. I'll leave this issue open so others can discover it.

**Comment by anshubansal2000** [comment]
@danjacobson-orbis Do you want to collaborate on this issue and other issues? I think this requires a code change and introduce a condition in cloudsplaining to honor "Condition Flag". Pls let me know if you want to collaborate. I am thinking to build a whole new module with nice UI.

**Comment by danjacobson-orbis** [comment]
@anshubansal2000 Thank you the offer to collaborate! I would like to eventually resolve this issue. However, as for building a new module with UI, my organization is running Cloudsplaining "headless", from code - so I won't be contributing to UI work on this project.

**Comment by danjacobson-orbis** [comment]
**Update:** I started tracing this through the code, and it appears the only place condition restrictions are checked in the codebase is in `statement_detail.py`: `StatementDetails.has_condition`.

That property is only checked by the code paths used for

- Privilege Escalation
- Data Exfiltration
- Credentials Exposure

So I'm guessing (haven't tested yet to confirm) that the presence of conditions will not suppress findings for any of

- Infrastructure Modification
- Resource Exposure
- Service Wildcard

Those three issue types use somewhat different methods of identifying problem actions (including calling out to Policy Sentry libraries), so the respective methods in either `statement_detail` (or `policy_document`, for Service Wildcard) are probably our targets for fixing this (assuming it is correct for Cloudsplaining to skip all finding types where conditions exist!)
