### ISSUE TITLE
is this solution runnable within a lambda

### ISSUE THREAD

**Issue by Angeo-Yorick** [salesforce/cloudsplaining#281]
I have installed this solution in many ways but got a few problem situations:
- It installs locally and works well
- It does not install on ec2 (results in a lot of issues with dependencies) P.S. tried with Amzon linux 2 and ubuntu image  
- After confirmed installation on ec2 the command is unrecognizable

The initial question from my end however is is there a pure lambda setup of the this solution? i.e. code deployable through lambda similar to how a tag alerter or cost alerter would work.

**Comment by kmcquade** [comment]
It sounds like the issue on EC2 has to do with your `PATH`. It probably does not have packages installed via python3 accessible on your path.

Others have done this setup in AWS Lambda. I don't have a ready to go example. But as covered in #39, it is possible since you can get the HTML output or JSON output as a string.
