### ISSUE TITLE
Support for roles

### ISSUE THREAD

**Issue by mrudrara** [salesforce/cloudsplaining#61]
Hi Team,
wondering if 'cloudsplaining download' support Roles or account ids for accessing different accounts. 
my company policy doesn't allow credentials in .aws/credentials file if I want to set up a single instance for all my environments

Thanks for your time

**Comment by kmcquade** [comment]
@mrudrara - `cloudsplaining download` uses the same authentication functionality as the AWS CLI - so, in this order shown below.

- Environment variables
- Shared credentials file
- EC2 Role

If you don't store credentials in the `~/.aws/credentials` file because it's on an EC2 instance, then you can still set the role in other accounts that you want to assume via the `role_arn` parameter in the credentials file, as shown here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html

```
[profile marketingadmin]
role_arn = arn:aws:iam::123456789012:role/marketingadminrole
credential_source = Ec2InstanceMetadata
```

Using the above example, the command would be:

```bash
cloudsplaining download --profile marketingadmin
```

Hope this helps.

**Comment by mrudrara** [comment]
Thanks for your valuable input. I took assume role approach and it works as you suggested. Thanks again for prompt reply

**Comment by kmcquade** [comment]
Sure thing, @mrudrara . I'll close this issue now. Let me know if you have any other questions!
